version: "3.9"

services:
  shopbot:
    build: .
    container_name: shopbot
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
